services:
  - type: web
    name: maxit-app
    env: web
    buildCommand: |
      # Installation de PHP et des dépendances
      apt-get update
      apt-get install -y php8.1-cli php8.1-fpm php8.1-pgsql php8.1-mbstring php8.1-xml php8.1-curl
      
      # Installation de Composer
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      
      # Installation des dépendances du projet
      composer install --no-dev
      
      # Exécution des migrations
      php migration.php
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        value: dpg-d221q115pdvs738gbss0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: maxit
      - key: DB_USER
        value: maxit_user
      - key: DB_PASSWORD
        value: BUJxqyXDS8MYceL1yVqPMu17yO7yaTT0
    healthCheckPath: /