services:
  - type: web
    name: maxit-app
    env: static
    runtime: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      apt-get update && apt-get install -y php8.1-cli php8.1-pgsql php8.1-mbstring
      composer install
      php migration.php
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        value: dpg-d221q115pdvs738gbss0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: maxit
      - key: DB_USER
        value: maxit_user
      - key: DB_PASSWORD
        value: BUJxqyXDS8MYceL1yVqPMu17yO7yaTT0