services:
  - type: web
    name: maxit-app
    env: php
    buildCommand: |
      composer install --no-dev
      php migration.php
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_DRIVER
        value: pgsql
      - key: DB_HOST
        value: dpg-d221q115pdvs738gbss0-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: maxit
      - key: DB_USER
        value: maxit_user
      - key: DB_PASSWORD
        value: BUJxqyXDS8MYceL1yVqPMu17yO7yaTT0
    healthCheckPath: /